services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    environment:
      - PORT=8000
      - MY_PROJECT=My FastAPI Project
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: restart
          path: backend/src

  # static_html:
  #   build: 
  #     context: ./static_html
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./static_html/src:/app

  db_service:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    # env_file:
    #   - .env.sample-db
    ports:
      - 5432:5432
    volumes:
      - managed_db_volume:/var/lib/postgresql/data

volumes:
  managed_db_volume: